# fly.toml app configuration file generated for blogging-website-sql on 2024-02-12T23:04:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blogging-website-sql'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source="myapp_data"
  destination="/data"